### ISSUE TITLE
mgui: font changes on Linux

### ISSUE THREAD

**Issue by SamoLasic** [markus-nilsson/md-dmri#11]
the increased font size on Linux renders labels in mgui unreadable

**Comment by markus-nilsson** [comment]
Is this still an issue?

**Comment by SamoLasic** [comment]
I haven’t run Matlab on Linux in a while.
Samo

On 28 Mar 2019, at 10:01, Markus Nilsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still an issue?

**Comment by markus-nilsson** [comment]
Ok -- I will close this issue for now -- let's see if it resurfaces when we get some Linux users
