### ISSUE TITLE
dtd_gamma is unstable in some voxels due to liberal bounds

### ISSUE THREAD

**Issue by filip-szczepankiewicz** [markus-nilsson/md-dmri#17]
The dtd_gamma fitting was very unbounded to support normal distributions of variance parameters close to zero. However, some voxels (mostly in lat ventricles) exhibit poor fitting performance. Solution may be to allow user to define lb and ub in dtd_gamma_opt.

**Comment by markus-nilsson** [comment]
Thanks. Adding this to the feature request list.
