### ISSUE TITLE
Use of xps_merge_clear_s_ind

### ISSUE THREAD

**Issue by filip-szczepankiewicz** [markus-nilsson/md-dmri#18]
Where is the opt filed "xps_merge_clear_s_ind" used?
What is its intended use?

I am currently implementing a control for series tracking in dtd_gamma. To turn off baseline signal adjustments, I employ the field "opt.dtd_gamma.do_multiseries" to effectively hide the data in s_ind from the fitting. Is this parameter "xps_merge_clear_s_ind" doing the same thing?

**Comment by markus-nilsson** [comment]
This field is no longer in use. Is now removed.
