### ISSUE TITLE
Error messages in assert statements seem incorrect

### ISSUE THREAD

**Issue by fnery** [markus-nilsson/md-dmri#23]
https://github.com/markus-nilsson/md-dmri/blob/882b6acb3aebf8be03d7fdd347b337ea2b180822/tools/tensor_maths/tm_tpars_to_1x6.m#L15

Should the assert message refer to a variable with 3 columns rather than 1? That is, should it read:
`'uvec should be (n or 1) x 3 in size'`? If so, the following probably also needs fixing:

https://github.com/markus-nilsson/md-dmri/blob/882b6acb3aebf8be03d7fdd347b337ea2b180822/tools/tensor_maths/tm_tpars_to_1x6.m#L23

**Comment by markus-nilsson** [comment]
Yes, you're right. This is now fixed.
