### ISSUE TITLE
Error in example/pipeline/step1_connect2data.m

### ISSUE THREAD

**Issue by abrarfaiyaz** [markus-nilsson/md-dmri#24]
When running with the mentioned dataset at step0, the following error is invoked at step1. (**Using Matlab/r2019a**)

```
Reference to non-existent field 'ref'.

Error in mgui_roi_gui_callback (line 220)
        EG = mgui_gui_volume_callback(EG, EG.roi.ref, hSender);
 
Error while evaluating UIControl Callback.
```

**Comment by markus-nilsson** [comment]
Thanks for the feedback, will deal with this in the next update!

**Comment by markus-nilsson** [comment]
I cannot reproduce this error – please raise a new issue if this can be reproduced with the new updates.
