### ISSUE TITLE
Typo in mdm_pa_ind_from_xps.m

### ISSUE THREAD

**Issue by RicardoRios46** [markus-nilsson/md-dmri#25]
Encountered an error while using the GUI. The error comes from a typo in line 39 in **mdm_pa_ind_from_xps.m**. The function "uniquetol" is written as "unqiuetol".

Saludos!

**Comment by markus-nilsson** [comment]
Thanks for the feedback! Will deal with this in the next update.

**Comment by markus-nilsson** [comment]
Now fixed, a year later but still...
