### ISSUE TITLE
xps.u does not describe symmetry axis for oblate b-tensors

### ISSUE THREAD

**Issue by filip-szczepankiewicz** [markus-nilsson/md-dmri#26]
When creating an xps from a list of b-tensors by calling `mdm_xps_from_bt`, the function tm_3x3_to_tpars is used (also) to fill in the field xps.u. According to the manual (https://github.com/markus-nilsson/md-dmri/blob/master/mdm/readme.txt), this field is the symmetry axis of the b-tensor, however, it appears that it is actually the eigenvector of the largest eigenvalue. Thus, this works for prolate b-tensors, but not oblate ones.

Thanks to M Cottaar and A Reymbaut for helpful discussions.

**Comment by filip-szczepankiewicz** [comment]
Perhaps the index of the most unique eigenvalue can be found like this:

[~, ind] = max(sum((L-L').^2,1));

where L is a 1x3 vector that contains the eigenvalues.

**Comment by markus-nilsson** [comment]
It now works, but for skewed tensors it returns NaNs as the symmetry axis is not defined
